[build]
builder = "dockerfile"

[deploy]
preDeployCommand = "php artisan migrate --force"
startCommand = 'bash -c "/var/www/start.sh"'
healthcheckPath = "/ping"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
